### ISSUE TITLE
Syntactic sugar for the controller syntax

### ISSUE THREAD

**Issue by StaverDmitry** [apneadiving/waterfall#10]
Hi! Thanks for the gem, I found it really handy to use in our project. 
I've been recently thinking about a kind of a syntactic sugar to make it look a bit more ruby-way. What I lack right now is the 'end' statement, it looks a bit odd for an eye in controller actions.
Would be great to have something like this:
```
Wf.new.start |flow| do
  flow.chain( ... )
  flow.chain( ... )
end
```
I've been kinda busy lately and wasn't able to take a look myself but do you think it's a possible improvement and what do you think about it?

**Comment by apneadiving** [comment]
Hi :)
I am not sure why you need it, but you could simply do:

    Wf.new.tap do |flow| 
      flow.chain( ... )
      flow.chain( ... )
    end

**Comment by StaverDmitry** [comment]
Oh, you're right, that will do the trick!
Thanks :)
