### ISSUE TITLE
Best way to test flows in flows.

### ISSUE THREAD

**Issue by anlek** [apneadiving/waterfall#11]
I'm trying to test a response from a flow but can't stub out a flow easily. I was wondering if there is a good way to do this in rspec?

Example:
https://gist.github.com/anlek/b32870a7326623f78affe26a9b931b49

**Comment by apneadiving** [comment]
Hi!
I forked your gist and added what I'd have done https://gist.github.com/apneadiving/2822ff791ad62e3f6c184a091eab0035

Hope it helps :)

**Comment by anlek** [comment]
That looks like what I was looking for, any chance it's something that would be useful in the library or maybe a second gem (`rspec-waterfall`)? Just a thought :)

**Comment by anlek** [comment]
Was able to test it and it worked great! Thanks for the response and the awesome gem!

**Comment by apneadiving** [comment]
Great, good news :)
The gem itself is super small, microlibrary style, spinning another one out of it feels overkill, especially for so few code.
Maybe an entry in the wiki would be more relevant?
Feel free to add it ;)

Cheers!

**Comment by anlek** [comment]
I'll look into adding it in the wiki.
I'm also wondering what is the best way to test the `reverse_flow`?

**Comment by apneadiving** [comment]
Here is a working setup:

```
class GuineaPig
  include Waterfall

  def call
  end

  def reverse_flow
    raise "have been triggered"
  end
end

Flow.new.chain { GuineaPig.new }.dam("just checking")
```

Adapt to your needs ;)

**Comment by anlek** [comment]
Sorry, I understand the setup, but how would you do a rspec test on that code?
Something like
```ruby
expect{GuineaPig.new.fail_now!}.to raise(StandardError, "have been triggered")
```
