### ISSUE TITLE
Feature: chain if

### ISSUE THREAD

**Issue by Austio** [apneadiving/waterfall#2]
What are your thoughts on having a conditional chain option in waterfall that will yield if the conditional evaluates to truthy?  I think would clean up things in rails controllers where you have to do logic and then continue the waterfall.  

Interface of something like

Wf.new
  .chain(var: :var, if: some_conditional) { stuff }

or introduce a new predicate

Wf.new
  .chain_if(some_conditional, var: :var) { stuff }

**Comment by apneadiving** [comment]
Lets brainstorm.

What would be the type(s) of `some_conditional`?

Would it be ok to evaluate it even if the waterfall is dammed?

**Comment by Austio** [comment]
I was thinking `some_conditional` would be a method that can be evaled, be it a method in current class or some class with full method like `UserSettings.something`

If Waterfall is dammed we would not eval the method (no need, results won't matter as this waterfall will be dammed)

**Comment by apneadiving** [comment]
Here are a few example of how it could be implemented
````ruby
#N1
self.chain_if(:foo, method_name)
#N2
self.chain_if(:foo, :method_name)
#N3
self.chain_if(:foo, -> { })
````

N1 would execute the method even if the waterfall is dammed, so we cant use it
N2
- `method_name` should refer to a method in the current context
- problem is it couldnt receive an argument from the outflow (useful whenever Wf.new is used), or the method signature should be enforced ( `def method_name(outflow)`)

N3 is too verbose

In the end, I'd say I prefer the mere:
````ruby
#4
self.chain(:foo) { if method_name ... }
````
