### ISSUE TITLE
Error transformation chain

### ISSUE THREAD

**Issue by flexoid** [apneadiving/waterfall#5]
Hi. I'm wondering if there's any better way to implement error transformation chain. Specifically, I want to transform error returned by nested waterfall.

For example, I have reusable ActionHandler, which performs action or dams with error string (sorry for the long listings, I'm trying to be verbose enough).

```ruby
class ActionHandler
  include Waterfall

  def initialize(action)
    @action = action
  end

  def call
    chain {}

    case @action
    when "start"
      chain { validate_start }
      chain { perform_start }
    when "stop"
      chain { validate_stop }
      chain { perform_stop }
    else
      dam("unknown action")
    end
  end

  def validate_start
    dam("cannot start") unless start_possible?
  end

  def validate_stop
    dam("cannot stop") unless stop_possible?
  end

  def start_possible?; false; end
  def stop_possible?; false; end

  def perform_start; end
  def perform_stop; end
end
```

And I want to use this action handler as one of the controller operation steps.

```ruby
class CreateOperation
  include Waterfall

  def call
    chain { validate_input }
    chain { handle_action }
  end

  def validate_input; end

  def handle_action
    ActionHandler.new(action)
  end
end

# Controller pseudo-code
Wf.new
  .chain { CreateOperation.new }
  .on_dam { |errors| render json: errors }
```

For this scenario, I need to transform string error into the error object:

```ruby
error = "cannot perform action"
errors = OpenStruct.new(errors: OpenStruct.new(messages: { action: [error] }))
```

So, as a workaround I define additional method on `ActionHandler`

```ruby
def chain_error
  on_dam do |error, _, waterfall|
    new_error = yield(error)
    waterfall.instance_variable_set("@error_pool", new_error) # hack
  end
end
```

and define `handle_action` as follows:

```ruby
def handle_action
  ActionHandler.new(action).call.chain_error do |error|
    OpenStruct.new(errors: OpenStruct.new(messages: { action: [error] }))
  end
end
```

What do you think, is it worth adding some kind of built-in mechanics into the lib to implement such scenarios more naturally? Waterfall is very flexible in case of chaining and transforming successful outcome value, but offers nothing when it comes to error value.

Thanks

**Comment by apneadiving** [comment]
Having different types of error containers can indeed be difficult to handle and you'd have to think about converting them each time you want to chain services.

What if you have something like:
```ruby
module Waterfall
  def add_error(key, value)
    OpenStruct.new(errors: OpenStruct.new(messages: { key => Array(value) }))
  end
end
```
Then use it like:
```ruby
def validate_stop
   dam(add_error("action", "cannot stop")) unless stop_possible?
end
```
Anyway I really recommend you settle for some kind of unique error object (I generally use ActiveModel::Error) but its your choice to make.

**Comment by flexoid** [comment]
It's more about different abstraction levels than different types. For instance, some validator can be part of low-level business login, returning some error codes, or even boolean value. But to reuse that piece of code in user-related interactions, I'll need to transform that error code into human-readable value, maybe even localized.

**Comment by apneadiving** [comment]
I understand what you mean.
Why not having something like:
```
Wf.new
  .chain { CreateOperation.new }
  .on_dam { |error_pool| render json: ErrorFormatter.new(error_pool).call }
```

And your `ErrorFormatter` would know how to convert your different errors for display?

**Comment by flexoid** [comment]
Yes, this is a possible solution. But imagine that `CreateOperation` is completely responsible for errors generation for the controller. I have some other validations in `CreateOperation#validate_input` method, which returns controller-ready error objects. And the desired solution will allow to combine errors from different levels by, regardless of their format.

In this solution, `ErrorFormatter` will have to know about all possible error sources and formats.

**Comment by apneadiving** [comment]
Yeah... or rely on rules like:
- if string then create real error out of conventions or mapping
- else use object itself (which would have to respond to `display_format` for instance)

I prefer to let people adapt it to their needs and keep the gem as light as possible

**Comment by flexoid** [comment]
Ok, I completely understand your intent to keep this library lightweight. Also you gave me some clues on how to implement my case, thanks for that. Probably this issue can be closed.

**Comment by apneadiving** [comment]
ok great, thanks for your inputs, its great to have feedback ;)
